name: example
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.13.0 <3.0.0'
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter

  app_core:
    path: ../

  # Restful
  retrofit: ^2.0.0-beta1
  json_annotation: ^4.0.1

  # Core libs
  get_it: ^6.1.0
  injectable: ^1.2.2

  get: ^4.1.4
  logger: ^1.0.0

  webview_flutter: ^2.0.4

  keyboard_service: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.12.2
  injectable_generator: ^1.2.2
  json_serializable: ^4.1.0
  retrofit_generator: ^2.0.0-beta3

flutter:
  uses-material-design: true